

services:
  app:
    image: ghcr.io/secretj12/loadtillx:latest
    build: .
    ports:
      - 5000:5000
    environment:
      - chargeTill=50
      - maxKwh=58
      - IP=0.0.0.0
      - PORT=5000
      - wattpilot_IP=$WATTPILOTIP
      - wattpilot_PW=$WATTPILOTPW
      - vw_username=$VWUSERNAME
      - vw_password=$VWPASSWORD